export const types = {
  GET_SUMMONER_INFO: "GET_SUMMONER_INFO",
  GET_SUMMONER_MATCHES: "GET_SUMMONER_MATCHES",
  GET_MATCH_INFO: "GET_MATCH_INFO",
  GET_SUMMONER_LEAGUE: "GET_SUMMONER_LEAGUE",
  GET_LEAGUE_INFO: "GET_LEAGUE_INFO",

  SET_SUMMONER_INFO_SUCCESS: "SET_SUMMONER_INFO_SUCCESS",
  SET_SUMMONER_MATCHES_SUCCESS: "SET_SUMMONER_MATCHES_SUCCESS",
  SET_MATCH_INFO_SUCCESS: "SET_MATCH_INFO_SUCCESS",
  SET_SUMMONER_LEAGUE_SUCCESS: "SET_SUMMONER_LEAGUE_SUCCESS",
  SET_LEAGUE_INFO_SUCCESS: "SET_LEAGUE_INFO_SUCCESS",
  SET_ACTION_ERROR: "SET_ACTION_ERROR",

  CLEAR_ACTION: "CLEAR_ACTION"

};
